-- Handwriting 누적 로드용 테이블 생성
-- Supabase SQL Editor에서 실행

-- 1. 테이블 생성
create table if not exists handwriting_files (
  id bigint generated by default as identity primary key,
  session_id text not null,
  storage_path text not null,
  created_at timestamptz default now(),
  client_id text
);

-- 2. 인덱스 추가 (조회 성능)
create index if not exists idx_handwriting_files_session_id
  on handwriting_files(session_id);

create index if not exists idx_handwriting_files_created_at
  on handwriting_files(created_at);

-- 3. RLS 활성화
alter table handwriting_files enable row level security;

-- 4. RLS 정책: anon이 읽기만 가능 (SELECT만 허용)
create policy "Allow public read by session"
  on handwriting_files for select
  to anon
  using (true);

-- 5. RLS 정책: service_role만 INSERT 가능 (Edge Function에서 사용)
-- (service_role은 RLS를 우회하므로 필요 없을 수도 있음)
create policy "Allow service_role insert"
  on handwriting_files for insert
  to service_role
  with check (true);

-- 6. 기존 Storage 파일들 수동 추가 (예시)
-- Storage에 있는 6개 파일의 경로를 이렇게 추가:
insert into handwriting_files (session_id, storage_path, created_at) values
  ('exhibition-2026', 'exhibition-2026/96278879-b5f5-408a-9d6e-6876bcc5fde3_2026-02-20T16:14:32.619Z_1ia0i1w.svg', '2026-02-20T16:14:32.619Z'::timestamptz),
  ('exhibition-2026', 'exhibition-2026/96278879-b5f5-408a-9d6e-6876bcc5fde3_2026-01-20T08:00:27.690Z_1i6wedx.svg', now()),
  ('exhibition-2026', 'exhibition-2026/96278879-b5f5-408a-9d6e-6876bcc5fde3_2026-02-20T15:46:12.764Z_2x3f8nn.svg', now()),
  ('exhibition-2026', 'exhibition-2026/96278879-b5f5-408a-9d6e-6876bcc5fde3_2026-02-20T15:56:39.834Z_7p14pat.svg', now()),
  ('exhibition-2026', 'exhibition-2026/97f6754c-4871-4d9f-873c-5147502c6f9f_2026-01-20T14:00:32.341Z_88wtk9h.svg', now());
